### ISSUE TITLE
Blog: Que es OGimage?

### ISSUE THREAD

**Issue by ibartomeus** [AbejasSilvestres/AASweb#10]

**Comment by thegrinder** [comment]
Es una imagen que aparece a la hora de compartir en facebook o whatsapp.

![CleanShot 2022-01-08 at 12 06 26](https://user-images.githubusercontent.com/14250944/148641827-e82ba2dd-38eb-4727-a85c-acf6bc386e3f.png)

No aparece en el blog post xq la imagen es muy grande (tiene que ser menos que 300k)

![CleanShot 2022-01-08 at 12 08 28](https://user-images.githubusercontent.com/14250944/148641861-590d3d12-aaf8-4c56-9651-678704a4683f.png)

He quitado el campo de `ogImage` en forestry pensando que simplemente puedo reutilizar `coverImage` pero por el tema del limite de 300kb, creo que habria que volver a ponerlo. Utilizariamos la imagen de buena calidad dentro de blog post y una version menos pesada para og:image

**Comment by ibartomeus** [comment]
Perfecto! Pues ya se como usarlo. Gracias. Cierro el issue.
