### ISSUE TITLE
Proyectos (fotod y videos)

### ISSUE THREAD

**Issue by ibartomeus** [AbejasSilvestres/AASweb#9]
En el proyecto HABEETAT he intentado embeber un video de youtube. Eso se puede?https://abejassilvestres.github.io/AASweb/projects/habeetat

He insertado una imagen, pero aparece rota.

**Comment by thegrinder** [comment]
La imagen ya esta bien 👍 Lo de video se deberia poder pero tengo que mirarlo

**Comment by thegrinder** [comment]
Hacer embed de los videos de youtube ya funciona. No iba antes porque el transformador de markdown a html no permitia elementos de html dentro de markdown (tipo `<p>` o `<iframe />`). Cambie los ajustes y ya todo va bien 👍

**Comment by ibartomeus** [comment]
Genial! Cierro isue.
